spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/titan_treasure?useUnicode=true&characterEncoding=utf8
        url: jdbc:mysql://172.27.64.1:3306/titan_treasure?useUnicode=true&characterEncoding=utf8
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: DinoStark
            password: non-feeling
    data:
        redis:
            host: localhost
            port: 10079

dubbo:
    service:
        titan-gate-be:
            url: tri://localhost:20880