server:
    port: 46258

spring:
    application:
        name: titan-treasure-be-core
    profiles:
        active: local
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: ALWAYS

dubbo:
    application:
        name: titan-treasure-be-core
    protocol:
        name: tri
        port: 20881
    consumer:
        check: false

mybatis:
    mapper-locations:
        - classpath:mappers/*.xml

logging:
    pattern:
        console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%thread]){faint} %clr(%-40.40logger{39}){cyan} %L %clr(:){faint} %m%n"
    level:
        root: INFO